### PR TITLE
Add ViperRxActivity and ViperRxFragment generators

### PR DESCRIPTION
**Pull request by jakubjodelka**

### CODE REVIEW

**Comment by mkoslacz** [comment]
Looks ok, but split it into separate commits for each template please (Activity/Fragment)

**Comment by jakubjodelka** [comment]
Now in separate commits

**Comment by mkoslacz** [comment]
New template names are overlapping with old ones, so Android Studio won't see them.

**Comment by jakubjodelka** [comment]
fixed.

**Comment by mkoslacz** [comment]
Rx Fragment with ViewHelper contract has no MoviperViewHelperRxRouting import. Instead it has MoviperRxRouting import. I asked you to test your changes.

**Comment by mkoslacz** [comment]
Now it's ok, thanks.

**Pull request merged**
